name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: aghakishiyeva
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=6DD19C&color_dots=94FFD4,6DD19C,46B47F
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=6DD19C&color_dots=0d1117,6DD19C,46B47F
      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
