name: Update Substack Posts

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://aghakishiyeva.substack.com/feed"
          max_post_count: 3
          readme_path: README.md
          comment_tag_name: BLOG-POST-LIST
          gh_token: ${{ secrets.GITHUB_TOKEN }}
